### ISSUE TITLE
UPID - explicitly validate string in Parse()

### ISSUE THREAD

**Issue by vladimirvivien** [mesosphere/mesos-go#22] opened 2014-08-23 23:49 UTC
Use regexp `[A-Za-z0-9_\-]+@[A-Za-z0-9_\-]+:[0-9]+` to validate parsed string.

**Comment by jdef** [comment] 2015-02-20 22:27
Probably want to include dots and avoid leading zeroes for ports:

`[A-Za-z0-9_\-]+@[A-Za-z0-9_\-\.]+:[1-9][0-9]*`

**Comment by tsenart** [comment] 2015-09-10 12:28
Duplicate of  #150

**Closed** 2015-09-10 12:29 UTC
Labels: enhancement
